apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-app
  template:
    metadata:
      labels:
        app: warehouse-app
    spec:
      containers:
        - name: warehouse-cont
          image: warehouse:1
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
              protocol: TCP
 