apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: prova
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: prova
  template: 
    metadata: 
      labels: 
        app: prova  
    spec: 
      containers: 
        - name: prova
          image: prova:latest
          imagePullPolicy: Never 
          ports:
            - containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prova
spec:
  type: LoadBalancer
  selector:
    app: prova
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
 