apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-app
  template:
    metadata:
      labels:
        app: orders-app
    spec:
      containers:
        - name: orders-cont
          image: orders:1
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
              protocol: TCP
 